# Generated by Django 4.0 on 2022-10-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_sub_category_alter_category_title'),
        ('product', '0006_brand_product_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brands', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام برند'),
        ),
    ]
